# Generated by Django 3.1 on 2020-08-29 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLocal', models.PositiveIntegerField()),
                ('nombreComercial', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('srcLogo', models.URLField()),
                ('likes', models.PositiveIntegerField()),
                ('estrellas', models.PositiveIntegerField()),
                ('vistas', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('adminLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TuristView.categoria')),
            ],
        ),
    ]
