# Generated by Django 3.1.1 on 2020-10-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='slogan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id_publicidad', models.AutoField(db_column='id_publicidad', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('src_imagen', models.ImageField(blank=True, db_column='src_imagen', null=True, upload_to='', verbose_name='Imagen')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
