# Generated by Django 3.1.3 on 2020-11-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='email address'),
        ),
    ]
