# Generated by Django 3.1.1 on 2020-10-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20201025_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicidad',
            options={'verbose_name': 'Publicidad', 'verbose_name_plural': 'Publicidades'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_comentario',
            field=models.AutoField(db_column='id_Comentario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='id_notificacion',
            field=models.AutoField(db_column='id_Notificacion', primary_key=True, serialize=False),
        ),
    ]
