# Generated by Django 3.1.1 on 2020-10-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20201025_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='Fecha_Creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
