# Generated by Django 3.1.1 on 2020-10-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_publicidad_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolpermiso',
            name='id_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rol_permiso', to='productos.permiso'),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rol_rolpermiso', to='productos.rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rol', to='productos.rol'),
        ),
    ]
